/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ApiPublicMigrateSchemaRouteImport } from './routes/api/public/migrate-schema'

const ApiPublicMigrateSchemaRoute = ApiPublicMigrateSchemaRouteImport.update({
  id: '/api/public/migrate-schema',
  path: '/api/public/migrate-schema',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/api/public/migrate-schema': typeof ApiPublicMigrateSchemaRoute
}
export interface FileRoutesByTo {
  '/api/public/migrate-schema': typeof ApiPublicMigrateSchemaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/api/public/migrate-schema': typeof ApiPublicMigrateSchemaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/api/public/migrate-schema'
  fileRoutesByTo: FileRoutesByTo
  to: '/api/public/migrate-schema'
  id: '__root__' | '/api/public/migrate-schema'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ApiPublicMigrateSchemaRoute: typeof ApiPublicMigrateSchemaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/api/public/migrate-schema': {
      id: '/api/public/migrate-schema'
      path: '/api/public/migrate-schema'
      fullPath: '/api/public/migrate-schema'
      preLoaderRoute: typeof ApiPublicMigrateSchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ApiPublicMigrateSchemaRoute: ApiPublicMigrateSchemaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
